swagger: '2.0'
info:
  title: Retrieve Account Details (Open Banking Standard)
  x-ibm-name: retrieve-account-details-open-banking-standard
  version: 1.0.0
schemes:
  - https
basePath: /OB-v312/IDBP-v1
produces:
  - application/json
consumes:
  - application/json
security:
  - AppID: []
    AppSecret: []
securityDefinitions:
  # UserOAuthSecurity:
  #   type: oauth2
  #   flow: accessCode
  #   x-ibm-oauth-provider: idbp-accounts-oauth-provider
  #   authorizationUrl: 'https://$(catalog.url)/idbp/account/oauthprov/oauth2/authorize'
  #   tokenUrl: 'https://$(catalog.url)/idbp/account/oauthprov/oauth2/token'
  #   scopes:
  #     account: For Accounts Read APIs
  AppSecret:
    type: apiKey
    name: X-Client-Secret
    in: header
    x-key-type: client_secret
  AppID:
    type: apiKey
    name: X-Client-Id
    in: header
    x-key-type: client_id
x-ibm-configuration:
  enforced: true
  testable: true
  phase: realized
  gateway: datapower-api-gateway
  type: rest
  cors:
    enabled: true
  assembly:
    execute:
      - switch:
          version: 2.0.0
          title: switch
          case:
            - condition: ($httpVerb() = 'GET' and $operationPath() = '/accounts')
              execute:
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: "var myAppConsoleLog = console.options({\n 'category': 'app_LC'\n});\nconst fileName = \"insertCIFAccIdGwysAccounts\"\nmyAppConsoleLog.debug('in ' + fileName);\n\ntry {\n\n    let token_metadata = context.get('oauth.verified_access_token.misc_info')\n    \n    myAppConsoleLog.error('**DEBUG : token_metadata: ', token_metadata)\n    myAppConsoleLog.error('**DEBUG : TYPEOF token_metadata: ', typeof(token_metadata))\n    token_metadata = token_metadata.slice(token_metadata.indexOf('a:') + 2)\n    myAppConsoleLog.error('**DEBUG : token_metadata after slice: ', token_metadata)\n    token_metadata = JSON.parse(token_metadata)\n    myAppConsoleLog.error('**DEBUG : TYPEOF token_metadata: ', typeof(token_metadata))\n    \n    myAppConsoleLog.error('**DEBUG : tokenmeta consentid: ', token_metadata['consentid'])\n    \n    let reqpath = context.get('request.path')\n    let tokenAccId = token_metadata['user_account']\n    let tokenPermissions = token_metadata['permissions']\n    let tokenUsername = token_metadata['username']\n    myAppConsoleLog.error('**DEBUG : tokenmeta reqpath: ', reqpath)\n    myAppConsoleLog.error('**DEBUG : tokenmeta tokenAccId: ', tokenAccId)\n    myAppConsoleLog.error('**DEBUG : tokenmeta tokenUsername: ', tokenUsername)\n    myAppConsoleLog.error('**DEBUG : tokenmeta tokenPermissions: ', tokenPermissions)\n\n    let backendURL = context.get('ace-all-acc-detail-by-cif-url')\n    backendURL = backendURL + 'custId=' + tokenUsername\n    myAppConsoleLog.error('**DEBUG : backendURL: ', backendURL)\n    context.set('backendURL',backendURL)\n\n\tcontext.message.header.set('permissions',tokenPermissions);\n\n\tcontext.message.header.set('clientorgname',context.get('client.org.name'))\n\tcontext.message.header.set('clientappname',context.get('client.app.name')) \n\tcontext.message.header.set('clientappid',context.get('client.app.id'))\n} catch (e) {\n    myAppConsoleLog.error('in ' + fileName + ' : ' + e);\n    context.set('custErrMsg','in insertCIFAccIdGwys : ' + e);\n\tcontext.reject('CustomError', 'GWISE500');\n}"
                - invoke:
                    version: 2.0.0
                    title: invoke
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - ConnectionError
                    target-url: $(backendURL)
            - condition: >-
                ($httpVerb() = 'GET' and $operationPath() =
                '/accounts/{accountid}')
              execute:
                - gatewayscript:
                    version: 2.0.0
                    title: gatewayscript
                    source: "var myAppConsoleLog = console.options({\n 'category': 'app_LC'\n});   \nconst fileName = \"insertCIFAccIdGwysAccounts\"\nmyAppConsoleLog.debug('in ' + fileName);\n\ntry {\n\n    let token_metadata = context.get('oauth.verified_access_token.misc_info')\n    \n    myAppConsoleLog.error('**DEBUG : token_metadata: ', token_metadata)\n    myAppConsoleLog.error('**DEBUG : TYPEOF token_metadata: ', typeof(token_metadata))\n    token_metadata = token_metadata.slice(token_metadata.indexOf('a:') + 2)\n    myAppConsoleLog.error('**DEBUG : token_metadata after slice: ', token_metadata)\n    token_metadata = JSON.parse(token_metadata)\n    myAppConsoleLog.error('**DEBUG : TYPEOF token_metadata: ', typeof(token_metadata))\n    \n    myAppConsoleLog.error('**DEBUG : tokenmeta consentid: ', token_metadata['consentid'])\n    \n    let reqpath = context.get('request.path')\n    let tokenAccId = token_metadata['user_account']\n    let tokenPermissions = token_metadata['permissions']\n    let tokenUsername = token_metadata['username']\n\n    myAppConsoleLog.error('**DEBUG : tokenmeta reqpath: ', reqpath)\n    myAppConsoleLog.error('**DEBUG : tokenmeta tokenAccId: ', tokenAccId)\n    myAppConsoleLog.error('**DEBUG : tokenmeta tokenUsername: ', tokenUsername)\n    myAppConsoleLog.error('**DEBUG : tokenmeta tokenPermissions: ', tokenPermissions)\n\n    //let reqAccId = reqpath.substr(reqpath.indexOf(\"/accounts/\") + \"/accounts/\".length)\n    //myAppConsoleLog.error('**DEBUG :  reqAccId: ', reqAccId)\n    let reqAccId = context.get('request.parameters.accountid')\n    reqAccId = reqAccId['values'][0]\n    myAppConsoleLog.error('**DEBUG :  reqAccId: ', reqAccId)\n\n    context.message.header.set('clientorgname',context.get('client.org.name'))\n\tcontext.message.header.set('clientappname',context.get('client.app.name')) \n\tcontext.message.header.set('clientappid',context.get('client.app.id'))\n\n    if(tokenAccId.includes(reqAccId)){\n        let backendURL = context.get('ace-one-acc-detail-by-accid-url')\n        backendURL = backendURL + 'custId=' + tokenUsername + '&AcctId=' + reqAccId\n        myAppConsoleLog.error('**DEBUG : backendURL: ', backendURL)\n        context.set('backendURL',backendURL)\n        \n        context.message.header.set('permissions',tokenPermissions);\n    }else{\n\t    myAppConsoleLog.error('in ' + fileName + ' : UnAuthorized AccountId');\n\t    context.set('custErrMsg','in ' + fileName + ' : UnAuthorized AccountId');\n\t\tcontext.reject('CustomError', 'GWICE400 UnAuthorized AccountID');\n    }\n} catch (e) {\n    myAppConsoleLog.error('in ' + fileName + ' : ' + e);\n    context.set('custErrMsg','in insertCIFAccIdGwys : ' + e);\n\tcontext.reject('CustomError', 'GWISE500');\n}"
                - invoke:
                    version: 2.0.0
                    title: invoke
                    header-control:
                      type: blacklist
                      values: []
                    parameter-control:
                      type: whitelist
                      values: []
                    timeout: 60
                    verb: keep
                    cache-response: protocol
                    cache-ttl: 900
                    stop-on-error:
                      - ConnectionError
                    target-url: $(backendURL)
  properties:
    target-url:
      value: 'http://example.com/operation-name'
      description: The URL of the target service
      encoded: false
    ace-all-acc-detail-by-cif-url:
      value: >-
        http://accountapi-http-ACENAMESPACE-CP4IDOMAIN/accounts/v1/getAccountsList?
    ace-one-acc-detail-by-accid-url:
      value: >-
        http://accountapi-http-ACENAMESPACE-CP4IDOMAIN/accounts/v1/getAccountDetails/?
  application-authentication:
    certificate: true
  activity-log:
    enabled: true
    error-content: header
    success-content: activity
parameters: {}
tags: []
definitions:
  AccountListResponse:
    description: ''
    type: object
    properties:
      Data:
        type: object
        properties:
          Account:
            type: array
            items:
              type: object
              properties:
                AccountId:
                  type: string
                Status:
                  type: string
                StatusUpdateDateTime:
                  type: string
                Currency:
                  type: string
                AccountType:
                  type: string
                AccountSubType:
                  type: string
                Nickname:
                  type: string
                Account:
                  type: array
                  items:
                    type: object
                    properties:
                      SchemeName:
                        type: string
                      Identification:
                        type: string
                      Name:
                        type: string
                      SecondaryIdentification:
                        type: string
      Risk:
        type: object
      Links:
        type: object
        properties:
          Self:
            type: string
      Meta:
        type: object
    example: >-
      {"Data": {"Account": [{"AccountId": "22289", "Status": "Enabled",
      "StatusUpdateDateTime": "2019-01-01T06:06:06+00:00", "Currency": "GBP",
      "AccountType": "Personal", "AccountSubType": "CurrentAccount", "Nickname":
      "Bills", "Account": [{"SchemeName": "UK.OBIE.SortCodeAccountNumber",
      "Identification": "80200110203345", "Name": "Mr Kevin",
      "SecondaryIdentification": "00021"} ] }, {"AccountId": "31820", "Status":
      "Enabled", "StatusUpdateDateTime": "2018-01-01T06:06:06+00:00",
      "Currency": "GBP", "AccountType": "Personal", "AccountSubType":
      "CurrentAccount", "Nickname": "Household", "Account": [{"SchemeName":
      "UK.OBIE.SortCodeAccountNumber", "Identification": "80200110203348",
      "Name": "Mr Kevin"} ] } ] }, "Links": {"Self":
      "https://api.alphabank.com/open-banking/v3.1/aisp/accounts/"}, "Meta":
      {"TotalPages": 1 } },      
paths:
  /accounts:
    get:
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/AccountListResponse'
      consumes: []
      produces: []
      security:
        # - UserOAuthSecurity:
        #     - account
        - AppSecret: []
          AppID: []
      operationId: retrieveAccountsForCIF
  '/accounts/{accountid}':
    get:
      responses:
        '200':
          description: success
          schema:
            $ref: '#/definitions/AccountListResponse'
      consumes: []
      produces: []
      security:
        # - UserOAuthSecurity:
        #     - account
        - AppSecret: []
          AppID: []
      operationId: retrieveAccountForAccId
    parameters:
      - name: accountid
        in: path
        required: true
        type: string
